
version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - dotnet restore
  build:
    commands:
      - echo "Building application"
      - dotnet build --configuration Release
      - dotnet test --logger trx
  post_build:
    commands:
      - echo "Running SonarCloud Analysis"
      - dotnet sonarscanner begin /k:"your_project_key" /o:"your_org" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="your_sonar_token"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.login="your_sonar_token"
artifacts:
  files:
    - '**/*'
